-- SEARCH PATH

SET search_path TO projet;

-- SCHEMA

DROP SCHEMA IF EXISTS projet CASCADE;
CREATE SCHEMA projet AUTHORIZATION projet;
GRANT ALL PRIVILEGES ON SCHEMA projet TO projet;

-- TABLES

CREATE TABLE Compte (
    IdCompte INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    Pseudo VARCHAR(25) NOT NULL,
    Nom VARCHAR(50) NOT NULL,
    Prenom VARCHAR(50) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    MotDePasse VARCHAR(100) NOT NULL,
    Credit DOUBLE PRECISION NOT NULL DEFAULT 0,
    PRIMARY KEY (IdCompte),
    UNIQUE(Pseudo, Email)
);

CREATE TABLE Role (
    IdCompte INT NOT NULL,
    Libelle VARCHAR(20) NOT NULL,
    CHECK(Libelle IN ('GESTIONNAIRE', 'USAGER')),
    FOREIGN KEY (IdCompte) REFERENCES compte (IdCompte),
    PRIMARY KEY (IdCompte, Libelle)
);

CREATE TABLE Produit (
    IdProduit INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    Nom VARCHAR(50) NOT NULL,
    Description VARCHAR(100) NOT NULL,
    Photo VARCHAR(25) NOT NULL,
    PrixMinimal DOUBLE PRECISION NOT NULL,
    DebutEnchere TIMESTAMP NOT NULL,
    FinEnchere TIMESTAMP NOT NULL,
    Cloturee BOOLEAN NOT NULL DEFAULT FALSE,
    IdAcheteur INT,
    IdVendeur INT NOT NULL,
    PRIMARY KEY(IdProduit),
    FOREIGN KEY (IdVendeur) REFERENCES compte (IdCompte),
    FOREIGN KEY (IdAcheteur) REFERENCES compte (IdCompte),
    UNIQUE(Nom)
);

CREATE TABLE Enchere (
    IdEnchere INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    IdProduit INT NOT NULL,
    Montant DOUBLE PRECISION NOT NULL,
    PRIMARY KEY(IdEnchere),
    FOREIGN KEY(IdProduit) REFERENCES Produit (IdProduit)
);

CREATE TABLE Mouvement (
    IdMouvement INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    IdCompte INT NOT NULL,
    TypeMouvement CHAR(1) NOT NULL,
    CHECK(TypeMouvement IN ('V', 'R')),
    Montant DOUBLE PRECISION NOT NULL,
    DateMouvement TIMESTAMP NOT NULL,
    PRIMARY KEY(IdMouvement),
    FOREIGN KEY (IdCompte) REFERENCES compte (IdCompte)
);
